# Generated by Django 6.0.2 on 2026-03-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_veiculo_cor_motorista_docs_frente_verso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='foto_bi',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='foto_carta',
        ),
        migrations.AddField(
            model_name='motorista',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='foto_livrete',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/livretes/'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='foto_veiculo',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/fotos/'),
        ),
    ]
