# Generated by Django 6.0.2 on 2026-04-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_motorista_foto_bi_remove_motorista_foto_carta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='primeira_viagem_gratis',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carga',
            name='categoria',
            field=models.CharField(choices=[('construcao', 'Materiais de Construção'), ('mobilia', 'Mobiliário/Casa'), ('eletro', 'Eletrodomésticos'), ('outros', 'Geral / Outros')], default='outros', max_length=20),
        ),
    ]
