# Generated by Django 6.0.2 on 2026-04-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_motorista_primeira_viagem_gratis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
