# Generated by Django 6.0.2 on 2026-04-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_carga_peso_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carga',
            name='peso_kg',
        ),
    ]
