# Generated by Django 6.0.2 on 2026-04-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_carga_peso_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='viagens_disponiveis',
            field=models.IntegerField(default=0, verbose_name='Viagens Disponíveis'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
