# Generated by Django 6.0.2 on 2026-04-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_motorista_viagens_disponiveis_alter_motorista_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITE', 'Aceite'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo da carteira (Kz)'),
        ),
    ]
