# Generated by Django 6.0.2 on 2026-04-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_carga_status_alter_motorista_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='documentos_enviados',
            field=models.BooleanField(default=False),
        ),
    ]
