# Generated by Django 6.0.2 on 2026-04-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_motorista_documentos_enviados'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='comentario_avaliacao',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário do Cliente'),
        ),
    ]
